import Head from "next/head";
import { Inter } from "next/font/google";

import { Container } from "react-bootstrap";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Feature from "@/components/Feature";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>CodeConquerors Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar></Navbar>
        <Container>
          <Hero></Hero>
          <Feature></Feature>
        </Container>
        <Footer></Footer>
      </main>
    </>
  );
}
